import pandas as pd
import numpy as np
import os
import glob

def calculate_rsi(data, window=14):
    delta = data['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=window).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=window).mean()
    rs = gain / loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def calculate_macd(data, slow=26, fast=12, signal=9):
    ema_fast = data['Close'].ewm(span=fast, adjust=False).mean()
    ema_slow = data['Close'].ewm(span=slow, adjust=False).mean()
    macd_line = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    macd_hist = macd_line - signal_line
    return macd_line, signal_line, macd_hist

def calculate_bollinger_bands(data, window=20, num_std=2):
    rolling_mean = data['Close'].rolling(window=window).mean()
    rolling_std = data['Close'].rolling(window=window).std()
    upper_band = rolling_mean + (rolling_std * num_std)
    lower_band = rolling_mean - (rolling_std * num_std)
    return upper_band, lower_band

def process_asset(file_path, output_dir):
    # Load data
    df = pd.read_csv(file_path)
    
    # Data Cleaning
    # Forward fill to prevent look-ahead bias, then backward fill for any initial NaNs
    df.ffill(inplace=True)
    df.bfill(inplace=True)
    
    # Feature Engineering
    # 1. Momentum & Returns
    df['Ret_1d'] = df['Close'].pct_change(1)
    df['Ret_5d'] = df['Close'].pct_change(5)
    
    # 2. RSI
    df['RSI_14'] = calculate_rsi(df, window=14)
    
    # 3. MACD
    df['MACD'], df['MACD_Signal'], df['MACD_Hist'] = calculate_macd(df)
    
    # 4. Trend (Moving Averages)
    df['SMA_10'] = df['Close'].rolling(window=10).mean()
    df['SMA_50'] = df['Close'].rolling(window=50).mean()
    df['Dist_SMA_50'] = (df['Close'] - df['SMA_50']) / df['SMA_50']
    
    # 5. Volatility
    df['BB_Upper'], df['BB_Lower'] = calculate_bollinger_bands(df, window=20)
    df['Vol_20d'] = df['Ret_1d'].rolling(window=20).std() * np.sqrt(252) # Annualized Historical Volatility
    
    # 6. Volume
    df['Vol_SMA_20'] = df['Volume'].rolling(window=20).mean()
    df['Vol_ROC'] = df['Volume'].pct_change(1)
    
    # Handle infinite values generated by pct_change (e.g. if Volume was 0)
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    
    # Forward fill again for any NaNs generated by feature engineering (like rolling windows)
    # Actually, we should leave initial NaNs from rolling windows as NaNs, so models know data is missing.
    # We will just save it as is.
    
    # Extract asset name from filename (e.g., Asset_001.csv)
    asset_name = os.path.basename(file_path)
    
    # Save to processed directory
    output_path = os.path.join(output_dir, asset_name)
    df.to_csv(output_path, index=False)
    # print(f"Processed and saved: {asset_name}")

def main():
    input_dir = 'anonymized_data'
    output_dir = 'processed_data'
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    csv_files = glob.glob(os.path.join(input_dir, '*.csv'))
    print(f"Found {len(csv_files)} files. Starting processing...")
    
    for idx, file in enumerate(csv_files):
        process_asset(file, output_dir)
        if (idx + 1) % 10 == 0:
            print(f"Processed {idx + 1}/{len(csv_files)} files.")
            
    print("Feature Engineering Complete!")

if __name__ == "__main__":
    main()
